import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from loop_engine.gamemaster.state_projector import SovereignStateProjector


class MarkdownProjector:
    """
    Generate local telemetry projections from Git metadata, selected filesystem
    observations, and local SQLite receipt records.

    These projections are deliberately not capability certification. Presence of
    code, tests, runners, or historical receipts cannot by itself upgrade a
    capability to VERIFIED.
    """

    def __init__(self, root_dir: Optional[Path] = None):
        self.root_dir = root_dir or PROJECT_ROOT
        self.state_projector = SovereignStateProjector(root_dir=self.root_dir)

    def generate_system_state_markdown(self) -> str:
        """Project a scoped local telemetry snapshot without self-certification."""
        hud = self.state_projector.project_hud()
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        lines = [
            "# SYSTEM_STATE: Local Telemetry Snapshot",
            "",
            "> **Scope warning:** this file reports local structural/runtime observations only. It is not repository qualification, CI health, or proof that a Shadow is operational. Current capability status is governed by `CAPABILITY_GROUND_TRUTH.md` and current verification evidence.",
            "",
            f"* **Generated At:** `{timestamp}`",
            f"* **Telemetry Schema:** `{hud.runtime_version}`",
            f"* **Git Branch:** `{hud.git_branch}` | **Physical Commit SHA:** `{hud.git_commit}`",
            f"* **Working Tree Clean:** `{'YES' if hud.working_tree_clean else 'NO'}`",
            f"* **Discovered loop_engine Test Files:** `{hud.discovered_test_files}`",
            f"* **Local Receipt Records:** `{hud.total_wal_receipts}`",
            "",
            "## 1. Domain Structural Presence",
            "",
            "The classifications below mean only that expected repository structures were observed. They do not mean the capability passed its tests or is operationally proven.",
            "",
            "| Shadow ID | Domain Name | Code Name | Structural Status | Module Present | Runner Present | Named Test Files | Local Receipts |",
            "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
        ]

        for domain in hud.domains:
            module_status = "YES" if domain.has_module else "NO"
            runner_status = "YES" if domain.has_runner else "NO"
            lines.append(
                f"| **Shadow {domain.shadow_id}** | {domain.name} | `{domain.code_name}` | **{domain.status}** | {module_status} | {runner_status} | {domain.test_files_count} | {domain.receipts_count} |"
            )

        lines.extend(
            [
                "",
                "## 2. Local Receipt Status Distribution",
                "",
                "Receipt counts are historical/runtime records from the local database. A `COMMITTED` receipt is not equivalent to current repository-wide verification.",
                "",
                "| Status | Count |",
                "| :--- | :--- |",
            ]
        )

        if hud.receipts_by_status:
            for status, count in sorted(hud.receipts_by_status.items()):
                lines.append(f"| `{status}` | {count} |")
        else:
            lines.append("| `NONE_RECORDED` | 0 |")

        lines.extend(
            [
                "",
                "---",
                "*This document is an automated local telemetry projection generated by `loop_engine.gamemaster.project_markdown`. It must not be used as a substitute for current verification evidence.*",
                "",
            ]
        )

        return "\n".join(lines)

    def generate_failure_ledger_markdown(self) -> str:
        """Project failures visible to the local receipts database query only."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        db_path = self.root_dir / "scratch" / "receipts.db"

        failures: List[Dict[str, Any]] = []
        query_error: Optional[str] = None
        if db_path.exists():
            try:
                conn = sqlite3.connect(str(db_path))
                conn.row_factory = sqlite3.Row
                rows = conn.execute(
                    "SELECT * FROM receipts WHERE failure_code IS NOT NULL OR status IN ('ABORTED', 'FAILED') ORDER BY id DESC"
                ).fetchall()
                failures = [dict(row) for row in rows]
                conn.close()
            except Exception as exc:
                query_error = type(exc).__name__

        lines = [
            "# FAILURE_LEDGER: Local Receipt Failure Projection",
            "",
            "> **Scope warning:** this file records only failures discoverable through the local receipt database query. Zero rows here does not mean CI is green, the repository is healthy, or no failures exist elsewhere.",
            "",
            f"* **Generated At:** `{timestamp}`",
            f"* **Failure Records Visible To This Query:** `{len(failures)}`",
            f"* **Receipt Database Present:** `{'YES' if db_path.exists() else 'NO'}`",
            "",
            "## 1. Governed Scar Rule Policy",
            "",
            "* **First Occurrence:** Record signature, root cause, and failure trace.",
            "* **Second Occurrence:** Mandatory taxonomy entry, scar registration, and dedicated regression test.",
            "* **Governing Change:** Propose rule or validator update with proof that prior golden routes remain unbroken.",
            "",
            "## 2. Logged Failure & Abort Records",
            "",
        ]

        if query_error:
            lines.append(f"*Failure query could not be completed (`{query_error}`). No health inference is permitted from this projection.*")
        elif failures:
            lines.extend(
                [
                    "| ID | Task ID | Domain | Failure Code | Repair Strategy | Strikes | Created At |",
                    "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
                ]
            )
            for failure in failures:
                lines.append(
                    f"| {failure.get('id')} | `{failure.get('task_id')}` | `{failure.get('domain_code')}` | `{failure.get('failure_code') or 'UNSPECIFIED'}` | {failure.get('repair_strategy') or 'None'} | {failure.get('strikes_used')} | {failure.get('created_at')} |"
                )
        else:
            lines.append(
                "*No failure rows were visible to this local receipt query. This is a narrow observation, not a repository-wide success claim.*"
            )

        lines.extend(
            [
                "",
                "---",
                "*This document is an automated local projection generated by `loop_engine.gamemaster.project_markdown`. Consult current CI and `CAPABILITY_GROUND_TRUTH.md` for broader system status.*",
                "",
            ]
        )

        return "\n".join(lines)

    def write_all(self) -> Dict[str, str]:
        """Write the two local telemetry projections to repository root."""
        state_md = self.generate_system_state_markdown()
        ledger_md = self.generate_failure_ledger_markdown()

        state_path = self.root_dir / "SYSTEM_STATE.md"
        ledger_path = self.root_dir / "FAILURE_LEDGER.md"

        state_path.write_text(state_md, encoding="utf-8")
        ledger_path.write_text(ledger_md, encoding="utf-8")

        return {
            "SYSTEM_STATE.md": str(state_path.as_posix()),
            "FAILURE_LEDGER.md": str(ledger_path.as_posix()),
        }


if __name__ == "__main__":
    projector = MarkdownProjector()
    written = projector.write_all()
    print(f"Projected state files: {written}")
