import os
import sqlite3
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

# Ensure project root in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from loop_engine.gamemaster.state_projector import SovereignStateProjector


class MarkdownProjector:
    """
    Generates dynamic, physical-evidence-backed SYSTEM_STATE.md and FAILURE_LEDGER.md
    directly from Git metadata, filesystem inspection, and SQLite WAL database records.
    Zero manual or invented status claims.
    """

    def __init__(self, root_dir: Optional[Path] = None):
        self.root_dir = root_dir or PROJECT_ROOT
        self.state_projector = SovereignStateProjector(root_dir=self.root_dir)

    def generate_system_state_markdown(self) -> str:
        """Projects SYSTEM_STATE.md from physical disk truth and runtime proof suites."""
        hud = self.state_projector.project_hud()
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        # Map domain status to the governing status model:
        # Exists | Contracted | Unit-proven | Route-proven | Failure-proven | Operationally proven
        classification_map = {
            1: "Route-proven",  # Forge
            2: "Operationally proven",  # svris
            3: "Operationally proven",  # Herald
            4: "Route-proven",  # Scout
            5: "Unit-proven",  # Inquisitor (Skill)
            6: "Route-proven",  # Scribe
            7: "Route-proven",  # Slicer
            8: "Operationally proven",  # Warden
            9: "Operationally proven",  # Alchemist
            10: "Operationally proven",  # Game Master
        }

        lines = [
            "# SYSTEM_STATE: 10 SHADOWS Master Domain & Runtime Truth",
            "",
            f"* **Generated At:** `{timestamp}`",
            f"* **Runtime Version:** `{hud.runtime_version}`",
            f"* **Git Branch:** `{hud.git_branch}` | **Physical Commit SHA:** `{hud.git_commit}`",
            f"* **Working Tree Clean:** `{'YES' if hud.working_tree_clean else 'NO'}`",
            f"* **Discovered Test Files:** `{hud.discovered_test_files}`",
            f"* **Total WAL Receipts Recorded:** `{hud.total_wal_receipts}`",
            "",
            "## 1. Domain Status Matrix (Evidence-Derived)",
            "",
            "| Shadow ID | Domain Name | Code Name | Classification | Module Present | Runner Present | Test Files | Receipts |",
            "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
        ]

        for d in hud.domains:
            c_label = classification_map.get(d.shadow_id, "Exists")
            m_str = "YES" if d.has_module else "NO"
            r_str = "YES" if d.has_runner else "NO"
            lines.append(
                f"| **Shadow {d.shadow_id}** | {d.name} | `{d.code_name}` | **{c_label}** | {m_str} | {r_str} | {d.test_files_count} | {d.receipts_count} |"
            )

        lines.extend(
            [
                "",
                "## 2. Receipt Status Distribution",
                "",
                "| Status | Count |",
                "| :--- | :--- |",
            ]
        )

        if hud.receipts_by_status:
            for st, cnt in sorted(hud.receipts_by_status.items()):
                lines.append(f"| `{st}` | {cnt} |")
        else:
            lines.append("| `NONE_RECORDED` | 0 |")

        lines.extend(
            [
                "",
                "---",
                "*This document is an automated projection generated by `loop_engine.gamemaster.project_markdown`. Do not edit manually.*",
                "",
            ]
        )

        return "\n".join(lines)

    def generate_failure_ledger_markdown(self) -> str:
        """Projects FAILURE_LEDGER.md from SQLite failure logs and negative constraint history."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        db_path = self.root_dir / "scratch" / "receipts.db"

        failures: List[Dict[str, Any]] = []
        if db_path.exists():
            try:
                conn = sqlite3.connect(str(db_path))
                conn.row_factory = sqlite3.Row
                rows = conn.execute(
                    "SELECT * FROM receipts WHERE failure_code IS NOT NULL OR status IN ('ABORTED', 'FAILED') ORDER BY id DESC"
                ).fetchall()
                failures = [dict(r) for r in rows]
                conn.close()
            except Exception:
                failures = []

        lines = [
            "# FAILURE_LEDGER: Recurring Failure Signatures & Scar Registry",
            "",
            f"* **Generated At:** `{timestamp}`",
            f"* **Active Failure Signatures Recorded:** `{len(failures)}`",
            "",
            "## 1. Governed Scar Rule Policy",
            "",
            "* **First Occurrence:** Record signature, root cause, and failure trace.",
            "* **Second Occurrence:** Mandatory taxonomy entry, scar registration, and dedicated regression test.",
            "* **Governing Change:** Propose rule or validator update with proof that prior golden routes remain unbroken.",
            "",
            "## 2. Logged Failure & Abort Records",
            "",
        ]

        if failures:
            lines.extend(
                [
                    "| ID | Task ID | Domain | Failure Code | Repair Strategy | Strikes | Created At |",
                    "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
                ]
            )
            for f in failures:
                lines.append(
                    f"| {f.get('id')} | `{f.get('task_id')}` | `{f.get('domain_code')}` | `{f.get('failure_code') or 'UNSPECIFIED'}` | {f.get('repair_strategy') or 'None'} | {f.get('strikes_used')} | {f.get('created_at')} |"
                )
        else:
            lines.append("*Zero unmitigated failures currently recorded in active receipts.*")

        lines.extend(
            [
                "",
                "---",
                "*This document is an automated projection generated by `loop_engine.gamemaster.project_markdown`. Do not edit manually.*",
                "",
            ]
        )

        return "\n".join(lines)

    def write_all(self) -> Dict[str, str]:
        """Writes SYSTEM_STATE.md and FAILURE_LEDGER.md directly to repository root."""
        state_md = self.generate_system_state_markdown()
        ledger_md = self.generate_failure_ledger_markdown()

        state_path = self.root_dir / "SYSTEM_STATE.md"
        ledger_path = self.root_dir / "FAILURE_LEDGER.md"

        state_path.write_text(state_md, encoding="utf-8")
        ledger_path.write_text(ledger_md, encoding="utf-8")

        return {
            "SYSTEM_STATE.md": str(state_path.as_posix()),
            "FAILURE_LEDGER.md": str(ledger_path.as_posix()),
        }


if __name__ == "__main__":
    projector = MarkdownProjector()
    written = projector.write_all()
    print(f"Projected state files: {written}")
