"""
deterministic_provider.py — Deterministic Test Worker Provider for 10 SHADOWS.
Enables comprehensive offline verification of authorization, dispatch, workspace isolation,
candidate sealing, repair loops, and promotion without consuming API tokens.
"""

from __future__ import annotations

import hashlib
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Tuple

from loop_engine.dispatcher.protocol import (
    ProviderUsage,
    WorkerAuthorization,
    WorkerEvidenceModality,
    WorkerExecutionResult,
)
from loop_engine.dispatcher.providers.base import WorkerProviderAdapter


def _run_git(args: List[str], cwd: Path) -> Tuple[int, str, str]:
    proc = subprocess.run(
        ["git"] + args,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        stdin=subprocess.DEVNULL,
    )
    return proc.returncode, proc.stdout.strip(), proc.stderr.strip()


class DeterministicWorkerAdapter(WorkerProviderAdapter):
    """
    Deterministic provider that generates reproducible, structured code mutations
    inside the governed workspace.
    """

    @property
    def provider_name(self) -> str:
        return "deterministic"

    def execute(
        self,
        auth: WorkerAuthorization,
        workspace_path: Path,
    ) -> WorkerExecutionResult:
        start_time = time.perf_counter()
        started_at = datetime.now(timezone.utc).isoformat()

        # Capture workspace before SHA
        _, before_sha, _ = _run_git(["rev-parse", "HEAD"], cwd=workspace_path)
        if not before_sha or len(before_sha) != 40:
            before_sha = auth.baseline_sha

        files_changed = []
        errors = []

        try:
            # Check for simulated error / repair triggers in objective
            obj_lower = auth.objective.lower()

            if "fail_attempt_1" in obj_lower and auth.attempt_number == 1:
                # Deliberate failure on attempt 1 for repair loop test
                test_file = workspace_path / "tests" / "test_deliberate_fail.py"
                test_file.parent.mkdir(parents=True, exist_ok=True)
                test_file.write_text(
                    "def test_failing_case(): assert False, 'Deliberate test failure'\n", encoding="utf-8"
                )
                files_changed.append("tests/test_deliberate_fail.py")
            elif "fail_attempt_1" in obj_lower and auth.attempt_number > 1:
                # Repaired on attempt 2!
                test_file = workspace_path / "tests" / "test_deliberate_fail.py"
                if test_file.exists():
                    test_file.unlink()
                feature_file = workspace_path / "src" / "repaired_module.py"
                feature_file.parent.mkdir(parents=True, exist_ok=True)
                feature_file.write_text("def repaired_fn(): return 'FIXED'\n", encoding="utf-8")
                files_changed.append("src/repaired_module.py")
            else:
                # Standard deterministic feature creation
                feature_file = workspace_path / "src" / "deterministic_feature.py"
                feature_file.parent.mkdir(parents=True, exist_ok=True)
                content = (
                    f"# Generated by Deterministic Worker for task {auth.task_id}\ndef run_feature():\n    return 42\n"
                )
                feature_file.write_text(content, encoding="utf-8")
                files_changed.append("src/deterministic_feature.py")

            # Stage & Commit changes inside the governed workspace
            _run_git(["add", "-A"], cwd=workspace_path)
            commit_msg = f"feat(governed): {auth.objective[:50]} (attempt {auth.attempt_number})"
            code, _, err = _run_git(["commit", "--no-verify", "-m", commit_msg], cwd=workspace_path)
            if code != 0:
                errors.append(f"Git commit inside workspace failed: {err}")

            # Capture workspace after SHA
            _, after_sha, _ = _run_git(["rev-parse", "HEAD"], cwd=workspace_path)
            if not after_sha or len(after_sha) != 40:
                after_sha = before_sha

            exit_status = "SUCCESS" if not errors else "FAILURE"
            output_digest = hashlib.sha256(f"{before_sha}:{after_sha}:{files_changed}".encode("utf-8")).hexdigest()

        except Exception as e:
            errors.append(f"Deterministic execution error: {type(e).__name__}: {str(e)}")
            exit_status = "FAILURE"
            after_sha = before_sha
            output_digest = hashlib.sha256(str(e).encode("utf-8")).hexdigest()

        duration = max(0.001, time.perf_counter() - start_time)
        ended_at = datetime.now(timezone.utc).isoformat()

        return WorkerExecutionResult(
            protocol_version="1.0.0",
            run_id=auth.run_id,
            invocation_id=auth.invocation_id,
            worker_id=auth.worker_id,
            requested_provider="deterministic",
            requested_model=auth.requested_model,
            resolved_provider="deterministic_test_harness",
            resolved_model="deterministic-v1",
            provider_invocation_id=f"det_inv_{auth.invocation_id}",
            modality=WorkerEvidenceModality.STRUCTURAL,
            started_at=started_at,
            ended_at=ended_at,
            duration_seconds=round(duration, 3),
            exit_status=exit_status,
            usage=ProviderUsage(prompt_tokens=10, candidate_tokens=20, total_tokens=30),
            output_digest=output_digest,
            workspace_before_sha=before_sha,
            workspace_after_sha=after_sha,
            files_changed=files_changed,
            provider_receipt=None,
            errors=errors,
            completion_status="COMPLETED",
        )
